s/progFonte/prog_fonte/g
s/fonteNome/fonte_nome/g
s/progAsm/prog_asm/g
s/asmNome/asm_nome/g
s/erroMsg/erro_msg/g
s/lexemaLido/lexema_lido/g
s/regLex/reg_lex/g
s/tabelaSimbolos/tabela_simbolos/g
s/printPilha/print_pilha/g
s/mostrarTabelaSimbolos/mostrar_tabela_simbolos/g
s/removeBranco/remove_branco/g
s/removeComentario/removeComentario/g
s/initPilha/init_pilha/g
s/iniciarCodegen/iniciar_codegen/g
s/inicializarTabela/iniciar_tabela/g
s/iniciarAnSin/iniciar_ansin/g
s/defTipo/def_tipo/g
s/defClasse/defClasse/g
s/toLogico/to_logico/g
s/verificaTam/verifica_tam/g
s/erroSintatico/erro_sintatico/g
s/verificaTipo/verifica_tipo/g
s/verificaClasse/verifica_classe/g
s/verificaDeclaracao/verifica_declaracao/g
s/verificaConst/verifica_const/g
s/verificaAtrVetor/verifica_atr_vetor/g
s/testeLexan/teste_lexan/g
s/testeColisao/teste_colisao/g
s/testeInsercao/teste_insercao/g
s/testeBuscaVazia/teste_busca_vazia/g
s/testeBuscaSimples/teste_busca_simples/g
s/testeBuscaEmColisao/teste_busca_colisao/g
s/pesquisarRegistro/pesquisar_registro/g
s/adicionarRegistro/adicionar_registro/g
s/limparTabela/limpar_tabela/g
s/buscaTipo/busca_tipo/g
s/adicionarReservados/adicionar_reservados/g
s/limparLista/limpar_lista/g
s/limparTabela/limpar_tabela/g
s/registroLex/registro_lex/g
s/posAtual/pos_atual/g
s/getChar/lex_get_char/g
s/ehLetra/eh_letra/g
s/ehDigito/eh_digito/g
s/ehBranco/eh_branco/g
s/removeAspas/remove_aspas/g
s/identificaToken/identifica_token/g
s/deletaPilha/deleta_pilha/g
s/novoTemp/novo_temp/g
s/novoRot/novo_rot/g
s/zeraTemp/zera_temp/g
s/atribuicaoString/atribuicao_string/g
s/genAtribuicao/gen_atribuicao/g
s/genExp/gen_exp/g
s/genDeclaracao/gen_declaracao/g
s/genRepeticao/gen_repeticao/g
s/genFimRepeticao/gen_fim_repeticao/g
s/genTeste/gen_teste/g
s/genElseTeste/gen_else_teste/g
s/genFimTeste/gen_fim_teste/g
s/initDeclaracao/init_declaracao/g
s/iniciarCodegen/iniciar_codegen/g
s/fimComandos/fim_comandos/g
s/fimDecInitCom/fim_dec_init_com/g
s/fatorGeraId/fator_gera_id/g
s/fatorGeraLiteral/fator_gera_literal/g
s/fatorGeraExp/fator_gera_exp/g
s/fatorGeraNot/fator_gera_not/g
s/fatorGeraArray/fator_gera_array/g
s/fatorGeraMenos/fator_gera_menos/g
s/atualizaPai/atualiza_pai/g
s/guardaOp/guarda_op/g
s/genOpTermos/gen_op_termos/g
s/compChar/comp_char/g
s/proxLinha/prox_linha/g
s/acessoArray/acesso_array/g
s/genEntrada/gen_entrada/g
s/genSaida/gen_saida/g
s/atrPos/atr_pos/g
s/atrTipo/atr_tipo/g
s/listaIds/lista_ids/g
s/expressaoS/expressao_s/g
s/blocoComandos/bloco_comandos/g
s/fimDeArquivo/fim_de_arquivo/g
s/casaToken/casa_token/g
